# Generated by Django 3.2.7 on 2021-09-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('postId', models.IntegerField()),
                ('senderId', models.IntegerField()),
                ('type', models.CharField(max_length=1)),
                ('status', models.DateField(verbose_name='%m-%d-%Y')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverId', models.IntegerField()),
                ('notoficationId', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.DateField(),
        ),
    ]
