# Generated by Django 3.2.7 on 2021-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ownerId', models.IntegerField()),
                ('status', models.DateField(verbose_name='%m-%d-%Y')),
                ('text', models.CharField(max_length=200)),
                ('image', models.IntegerField()),
            ],
        ),
    ]
